#ifndef _PR_ERROR_H_
#define _PR_ERROR_H_


/****************************************************************************
 ****************************************************************************
 *            PowerShot RemoteCapture SDK : ResponseCode Summary            *
 ****************************************************************************
 ****************************************************************************/

/*-----------------------------------------------------------------------
   PRSDK Error Code Masks
------------------------------------------------------------------------*/
#define prERROR_COMPONENTID_MASK					0x00F00000L
#define prERROR_ERRORID_MASK						0x0000FFFFL


/*-----------------------------------------------------------------------
   PRSDK Base Component IDs
------------------------------------------------------------------------*/
#define prERROR_PTP_COMPONENTID				  		0x00100000L		/* PTP operation errors */
#define prERROR_PRSDK_COMPONENTID				  	0x00200000L		/* PRSDK Internal Error */
#define prERROR_WIA_STI_COMPONENTID				 	0x00300000L		/* Errors generated by the Windows WIA/STI */
#define prERROR_WINDOWS_COMPONENTID	  				0x00400000L		/* Errors generated by the GetLastError() function in WIN32 API*/
#define prERROR_COMIF_COMPONENTID	  				0x00500000L		/* Windows COM I/F errors */

/*-----------------------------------------------------------------------
   PRSDK Functin Success Code
------------------------------------------------------------------------*/
#define prOK										0x00000000L


/*-----------------------------------------------------------------------
   PTP Operation Error IDs
------------------------------------------------------------------------*/
#define prRESPONSE_Undefined				  				0x00002000
#define prRESPONSE_GeneralError				  				0x00002002
#define prRESPONSE_SessionNotOpen							0x00002003
#define prRESPONSE_InvalidTransactionID						0x00002004
#define prRESPONSE_OperationNotSupported					0x00002005
#define prRESPONSE_ParameterNotSupported					0x00002006
#define prRESPONSE_IncompleteTransfer						0x00002007
#define prRESPONSE_InvalidStorageID							0x00002008
#define prRESPONSE_InvalidObjectHandle						0x00002009
#define prRESPONSE_DevicePropNotSupported					0x0000200A
#define prRESPONSE_InvalidObjectFormatCode					0x0000200B
#define prRESPONSE_StoreFull				  				0x0000200C
#define prRESPONSE_ObjectWriteProtected						0x0000200D
#define prRESPONSE_StoreRead_Only							0x0000200E
#define prRESPONSE_AccessDenied							  	0x0000200F
#define prRESPONSE_NoThumbnailPresent						0x00002010
#define prRESPONSE_SelfTestFailed							0x00002011
#define prRESPONSE_PartialDeletion							0x00002012
#define prRESPONSE_StoreNotAvailable						0x00002013
#define prRESPONSE_SpecificationByFormatUnsupported			0x00002014
#define prRESPONSE_NoValidObjectInfo						0x00002015
#define prRESPONSE_InvalidCodeFormat						0x00002016
#define prRESPONSE_UnknownVendorCode						0x00002017
#define prRESPONSE_CaptureAlreadyTerminated					0x00002018
#define prRESPONSE_DeviceBusy				  				0x00002019
#define prRESPONSE_InvalidParentObject						0x0000201A
#define prRESPONSE_InvalidDevicePropFormat					0x0000201B
#define prRESPONSE_InvalidDevicePropValue					0x0000201C
#define prRESPONSE_InvalidParameter							0x0000201D
#define prRESPONSE_SessionAlreadyOpen						0x0000201E
#define prRESPONSE_TransactionCancelled						0x0000201F
#define prRESPONSE_SpecificationOfDestinationUnsupported	0x00002020

/* Vendor Extension Error IDs */
#define prRESPONSE_Ex_Undefined								0x0000A000
#define prRESPONSE_Ex_UnknownCommandReceived				0x0000A001
#define prRESPONSE_Ex_MemAllocFailed						0x0000A002
#define prRESPONSE_Ex_InternalError							0x0000A003
#define prRESPONSE_Ex_DirIOError							0x0000A004
#define prRESPONSE_Ex_RefusedByOtherProcess					0x0000A005
#define prRESPONSE_Ex_CoverClosed							0x0000A006
#define prRESPONSE_Ex_NoRelease								0x0000A007
#define prRESPONSE_Ex_DeviceIsHot							0x0000A008
#define prRESPONSE_Ex_LowBattery							0x0000A009
#define prRESPONSE_Ex_AlreadyExit							0x0000A00A

/*-----------------------------------------------------------------------
   PRSDK Internal Error IDs
------------------------------------------------------------------------*/
/* Miscellaneous errors */
#define prUNIMPLEMENTED               						0x00000001L
#define prINTERNAL_ERROR									0x00000002L
#define prMEM_ALLOC_FAILED					  				0x00000003L
#define prMEM_FREE_FAILED									0x00000004L
#define prOPERATION_CANCELLED								0x00000005L
#define prINCOMPATIBLE_VERSION								0x00000006L
#define prNOT_SUPPORTED							  			0x00000007L
#define prUNEXPECTED_EXCEPTION								0x00000008L
#define prPROTECTION_VIOLATION								0x00000009L
#define prMISSING_SUBCOMPONENT								0x0000000AL
#define prSELECTION_UNAVAILABLE								0x0000000BL

/* Function Parameter errors */
#define prINVALID_PARAMETER									0x00000021L
#define prINVALID_HANDLE						  			0x00000022L

/* ... */
#define prINVALID_FN_CALL									0x00000061L
#define prWAIT_TIMEOUT_ERROR					    		0x00000062L
#define prINSUFFICIENT_BUFFER					    		0x00000063L
#define prEVENT_CALLBACK_EXIST					    		0x00000064L

#endif

