unit prError;

interface

const
{ ****************************************************************************
  ****************************************************************************
  *            PowerShot RemoteCapture SDK : ResponseCode Summary            *
  ****************************************************************************
  **************************************************************************** }

{ -----------------------------------------------------------------------
   PRSDK Error Code Masks
------------------------------------------------------------------------ }
  prERROR_COMPONENTID_MASK = $00F00000;
  prERROR_ERRORID_MASK		 = $0000FFFF;


{ -----------------------------------------------------------------------
   PRSDK Base Component IDs
------------------------------------------------------------------------ }
  prERROR_PTP_COMPONENTID	    = $00100000;		{ PTP operation errors }
  prERROR_PRSDK_COMPONENTID		= $00200000;		{ PRSDK Internal Error }
  prERROR_WIA_STI_COMPONENTID = $00300000;		{ Errors generated by the Windows WIA/STI }
  prERROR_WINDOWS_COMPONENTID	= $00400000;		{ Errors generated by the GetLastError() function in WIN32 API}
  prERROR_COMIF_COMPONENTID	  = $00500000;		{ Windows COM I/F errors }

{ -----------------------------------------------------------------------
   PRSDK Functin Success Code
------------------------------------------------------------------------ }
  prOK = $00000000;


{ -----------------------------------------------------------------------
   PTP Operation Error IDs
------------------------------------------------------------------------ }
  prRESPONSE_Undefined				  				            = $00002000;
  prRESPONSE_GeneralError				  				          = $00002002;
  prRESPONSE_SessionNotOpen							            = $00002003;
  prRESPONSE_InvalidTransactionID						        = $00002004;
  prRESPONSE_OperationNotSupported					        = $00002005;
  prRESPONSE_ParameterNotSupported					        = $00002006;
  prRESPONSE_IncompleteTransfer						          = $00002007;
  prRESPONSE_InvalidStorageID							          = $00002008;
  prRESPONSE_InvalidObjectHandle						        = $00002009;
  prRESPONSE_DevicePropNotSupported					        = $0000200A;
  prRESPONSE_InvalidObjectFormatCode					      = $0000200B;
  prRESPONSE_StoreFull				  				            = $0000200C;
  prRESPONSE_ObjectWriteProtected						        = $0000200D;
  prRESPONSE_StoreRead_Only							            = $0000200E;
  prRESPONSE_AccessDenied							  	          = $0000200F;
  prRESPONSE_NoThumbnailPresent						          = $00002010;
  prRESPONSE_SelfTestFailed							            = $00002011;
  prRESPONSE_PartialDeletion							          = $00002012;
  prRESPONSE_StoreNotAvailable						          = $00002013;
  prRESPONSE_SpecificationByFormatUnsupported	      = $00002014;
  prRESPONSE_NoValidObjectInfo						          = $00002015;
  prRESPONSE_InvalidCodeFormat						          = $00002016;
  prRESPONSE_UnknownVendorCode						          = $00002017;
  prRESPONSE_CaptureAlreadyTerminated					      = $00002018;
  prRESPONSE_DeviceBusy				  				            = $00002019;
  prRESPONSE_InvalidParentObject						        = $0000201A;
  prRESPONSE_InvalidDevicePropFormat					      = $0000201B;
  prRESPONSE_InvalidDevicePropValue					        = $0000201C;
  prRESPONSE_InvalidParameter							          = $0000201D;
  prRESPONSE_SessionAlreadyOpen						          = $0000201E;
  prRESPONSE_TransactionCancelled						        = $0000201F;
  prRESPONSE_SpecificationOfDestinationUnsupported  = $00002020;

{ Vendor Extension Error IDs }
  prRESPONSE_Ex_Undefined								= $0000A000;
  prRESPONSE_Ex_UnknownCommandReceived	= $0000A001;
  prRESPONSE_Ex_MemAllocFailed					= $0000A002;
  prRESPONSE_Ex_InternalError						= $0000A003;
  prRESPONSE_Ex_DirIOError							= $0000A004;
  prRESPONSE_Ex_RefusedByOtherProcess		= $0000A005;
  prRESPONSE_Ex_CoverClosed							= $0000A006;
  prRESPONSE_Ex_NoRelease								= $0000A007;
  prRESPONSE_Ex_DeviceIsHot							= $0000A008;
  prRESPONSE_Ex_LowBattery							= $0000A009;
  prRESPONSE_Ex_AlreadyExit							= $0000A00A;

{ -----------------------------------------------------------------------
   PRSDK Internal Error IDs
------------------------------------------------------------------------ }
{ Miscellaneous errors }
  prUNIMPLEMENTED         = $00000001;
  prINTERNAL_ERROR				= $00000002;
  prMEM_ALLOC_FAILED			= $00000003;
  prMEM_FREE_FAILED				= $00000004;
  prOPERATION_CANCELLED		= $00000005;
  prINCOMPATIBLE_VERSION	= $00000006;
  prNOT_SUPPORTED					= $00000007;
  prUNEXPECTED_EXCEPTION	= $00000008;
  prPROTECTION_VIOLATION	= $00000009;
  prMISSING_SUBCOMPONENT	= $0000000A;
  prSELECTION_UNAVAILABLE = $0000000B;

{ Function Parameter errors }
  prINVALID_PARAMETER = $00000021;
  prINVALID_HANDLE		= $00000022;

{ ... }
  prINVALID_FN_CALL				= $00000061;
  prWAIT_TIMEOUT_ERROR		= $00000062;
  prINSUFFICIENT_BUFFER	  = $00000063;
  prEVENT_CALLBACK_EXIST  = $00000064;


implementation

end.
