object Form2: TForm2
  Left = 720
  Top = 459
  AlphaBlendValue = 20
  Caption = 't'
  ClientHeight = 249
  ClientWidth = 245
  Color = clBlack
  TransparentColorValue = 98432
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  Position = poDesigned
  Visible = True
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 13
end
