{$R FBEmbedded_32_2_5_0.res}
const FFilemap =
'32_2_5_0_fbembed.dll=fbembed.dll;'+
'32_2_5_0_icudt30.dll=icudt30.dll;'+
'32_2_5_0_icuuc30.dll=icuuc30.dll;'+
'32_2_5_0_Microsoft.VC80.CRT.manifest=Microsoft.VC80.CRT.manifest;'+
'32_2_5_0_msvcp80.dll=msvcp80.dll;'+
'32_2_5_0_msvcr80.dll=msvcr80.dll;'+
'32_2_5_0_fbintl.conf=intl\fbintl.conf;'+
'32_2_5_0_fbintl.dll=intl\fbintl.dll';
const FLibName = 'fbembed.dll';
